### PR TITLE
Updated jade dependency from ~1.9.2 to ~1.11.0

### PR DESCRIPTION
**Pull request by romanpitak**
Jade added `jstransformers` support in v1.10.0 which allows easy creation of custom filters.

### CODE REVIEW

**Comment by balupton** [comment]
@romanpitak what is your npm username? I'll add you to the extras team and give you publish access. 😊

This will be a minor version bump for the jade plugin, and release process can be found via https://github.com/docpad/docpad-plugin-jade/blob/master/CONTRIBUTING.md

**Comment by romanpitak** [comment]
@balupton my npm username is `romanpitak`

I'll make sure to (continue to) stick to the guidelines.

Thanks :)

**Comment by romanpitak** [comment]
@balupton I'm also noticing outdated dependencies in other plugins (e.g. sitemap, but almost all of them have outdated dependencies) and outdated links in the documentation. I could fix some of them if you're interested. Would you prefer me to issue pull requests, or would you rather just grant me push access?

I'd also like to add some notes on using JSTransformers into the `docpad-plugin-jade` README file as this is the new way to go for Jade. Standard Transformers support will be dropped in Jade v2.0.0 and is marked as deprecased since v1.10.0. Will you be ok with that?

[jade changelog](http://jade-lang.com/history/)

**Comment by balupton** [comment]
> @balupton my npm username is romanpitak
> 
> I'll make sure to (continue to) stick to the guidelines.

Fantastic, you now have publish access to the jade plugin, and have been added as a member of the docpad extras team



> @balupton I'm also noticing outdated dependencies in other plugins (e.g. sitemap, but almost all of them have outdated dependencies) and outdated links in the documentation. I could fix some of them if you're interested. Would you prefer me to issue pull requests, or would you rather just grant me push access?
> 
> I'd also like to add some notes on using JSTransformers into the docpad-plugin-jade README file as this is the new way to go for Jade. Standard Transformers support will be dropped in Jade v2.0.0 and is marked as deprecased since v1.10.0. Will you be ok with that?

Up to you, if in doubt, would like a review, or just to notify me, do a pull request - I'm pretty active these days so will get to it in a day or two. Otherwise, feel free to publish without me.

**Pull request merged**
