### PR TITLE
Fix #20: Migrate to Pug

### LINKED ISSUE #20: Jade to Pug Migration
As far as I am know, jade will cease to exist and change to pug. Hence, I guess this plugin should be updated.

### PR DESCRIPTION
**Pull request by craigmdennis**
# Migration from Jade to Pug
It's pretty much a straight swap so it wasn't that difficult. I'm not an expert though so there may be some underlying properties of Pug that need to be exposed in a different way. Having said that, all tests pass and the renderer works fine; including attribute interpolation using ES6 template literals.

## A few things to note:
- The current version of Pug is a beta version `2.0.0-beta11`
- I've updated all references to `docpad-plugin-jade` to be `docpad-plugin-pug`
- I have NOT updated the HISTORY as I'm unsure if this is auto-generated from commits
- I have NOT updated the version number as I'm unsure if this should be a major version bump (I am aware of the special meaning behind `v1` and `v2` after reading the plugin docs).

## Changing the repo name
References to the repo `docpad-plugin-jade` have been updated to be `docpad-plugin-pug`
This is because this repo _should_ be renamed to reflect the new renderer, and I believe [GitHub will redirect from the old to the new automatically](https://github.com/blog/1508-repository-redirects-are-here).

I have no idea if any of this is correct etiquette ¯\_(ツ)_/¯
Please provide some next steps to get this merged.

## To Do
- [ ] Update version number
- [ ] Update HISTORY
- [ ] Rename repo

### CODE REVIEW

**Comment by mikeumus** [comment]
Thanks for the PR @craigmdennis

Were you able to test this in a DocPad app to see it running fine?

**Comment by craigmdennis** [comment]
@mikeumus Tested using `cake test` as well as running in a fresh DocPad project running locally (I added it to the `/plugins/` directory and everything compiled fine)

**Comment by balupton** [comment]
Perhaps we should release this is a new plugin at `docpad-plugin-jade` and have this repo/plugin be deprecated and link to the pug plugin.

While DocPad v6 plugins are stuck on the v2 namespace, the plugins can only make use of minor 2.x releases - which should not include backwards compatibility breaks.

I would do this as a minor bump, however as jade => pug is a different package, doing as a new plugin makes sense.

**Comment by balupton** [comment]
Okay created https://github.com/docpad/docpad-plugin-pug and added @craigmdennis to the extras team, so you have push access. When you do the v2.0.0 release - just note that it is a fork from `docapd-plugin-jade`, and after the publish, do a `npm owner add bevry` so the rest of the team can maintain too.

**Comment by craigmdennis** [comment]
@balupton Sounds like a plan. Want me to keep it in the same branch, then PR in the new repo?

**Comment by balupton** [comment]
@craigmdennis happy for you to push up, publish, etc directly to the new repo :)

**Comment by craigmdennis** [comment]
@balupton All done. Going to open a new PR on this repo with deprecation notice.

**Pull request closed without merging**
